parameters:
  dependsOn: 'Build'
  pesterVersion: ''
  specDirectory: '$(Build.SourcesDirectory)/Specs'
  includeTag: []
  excludeTag: []
  additionalModulePaths: ''
  artifactName: 'Module'
  stagingDirectory: '$(Build.ArtifactStagingDirectory)'
  codeCoverageDirectory: '$(Build.ArtifactStagingDirectory)'
  show: 'All'
  pool:
    vmImage: 'windows-2019'

jobs:
  - job: PesterGherkin
    dependsOn: ${{ parameters.dependsOn }}

    pool: ${{ parameters.pool }}

    steps:
    - checkout: self
      lfs: true

    - template: InstallRequiredModules-step.yml
      parameters:
        Destination: $(Build.SourcesDirectory)/RequiredModules

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Build Artifacts'
      condition: ${{ ne('', parameters.artifactName)}}
      inputs:
        artifactName: ${{ parameters.artifactName }}
        downloadPath: ${{ parameters.artifactDownloadDirectory }}

    - template: Gherkin-step.yml
      parameters:
        pesterVersion: ${{ parameters.pesterVersion }}
        specDirectory: ${{ parameters.specDirectory }}
        includeTag: ${{ parameters.includeTag }}
        excludeTag: ${{ parameters.excludeTag }}
        additionalModulePath: "${{ parameters.stagingDirectory }};${{ parameters.additionalModulePaths }};$(Build.SourcesDirectory)/RequiredModules"
        codeCoverageDirectory: ${{ parameters.codeCoverageDirectory }}
        show: ${{ parameters.show }}