parameters:
  pesterVersion: ''
  specDirectory: '$(Build.SourcesDirectory)/Specs'
  requiredModulesPath: RequiredModules.psd1
  artifactName: ''
  artifactDownloadDirectory: '$(Build.ArtifactStagingDirectory)'
  additionalModulePaths: []
  codeCoverageDirectory: ''
  dependsOn: []
  includeTag: []
  excludeTag: []
  cleanJob: ''
  show: 'All'
  pool:
    vmImage: 'windows-2019'

jobs:
  - job: PesterGherkin
    dependsOn: ${{ parameters.dependsOn }}
    ${{ if ne(parameters.cleanJob, '') }}:
      workspace:
        clean: ${{ parameters.cleanJob }}

    pool: ${{ parameters.pool }}

    steps:
    - checkout: self # re-checkout, because we don't package tests
      fetchDepth: 1  # we only need the current tests
      lfs: true

    - template: Install-RequiredModule-step.yml
      parameters:
        path: $(Build.SourcesDirectory)/${{ parameters.requiredModulesPath }}

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Build Artifacts'
      condition: ${{ ne('', parameters.artifactName)}}
      inputs:
        artifactName: ${{ parameters.artifactName }}
        downloadPath: ${{ parameters.artifactDownloadDirectory }}/$(Build.DefinitionName)

    - template: Gherkin-step.yml
      parameters:
        pesterVersion: ${{ parameters.pesterVersion }}
        specDirectory: ${{ parameters.specDirectory }}
        includeTag: ${{ parameters.includeTag }}
        excludeTag: ${{ parameters.excludeTag }}
        additionalModulePath: ${{ parameters.artifactDownloadDirectory }};${{ parameters.additionalModulePath }}
        codeCoverageDirectory: ${{ parameters.codeCoverageDirectory }}
        show: ${{ parameters.show }}