parameters:
  dependsOn: 'Build'
  artifactName: 'Module'
  stagingDirectory: '$(Build.ArtifactStagingDirectory)'
  testsDirectory: '$(Build.SourcesDirectory)/Tests'
  includeTag: ''
  excludeTag: ''
  pool:
    vmImage: 'windows-2019'

jobs:
  - job: Pester
    dependsOn: ${{ parameters.dependsOn }}

    pool: ${{ parameters.pool }}

    steps:
    - checkout: self
      lfs: true

    - task: DownloadPipelineArtifact@1
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: ${{ parameters.artifactName }}
        downloadPath: ${{ parameters.stagingDirectory }}
        itemPattern: '**/*'

    - template: InstallRequiredModules-step.yml

    - template: Pester-step.yml
      parameters:
        testsDirectory: '$(Build.SourcesDirectory)/Tests'
        includeTag: ${{ parameters.includeTag }}
        excludeTag: ${{ parameters.excludeTag }}
        additionalModulePath: ${{ parameters.stagingDirectory }}
        codeCoverageDirectory: ${{ parameters.stagingDirectory }}
        show: 'Default'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: '$(Common.TestResultsDirectory)/Test-$(Build.SourceVersion).xml'
        searchFolder: '$(Common.TestResultsDirectory)'
      condition: succeededOrFailed()

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage'
      inputs:
        summaryFileLocation: '$(Common.TestResultsDirectory)/Coverage-$(Build.SourceVersion).xml'
      condition: succeededOrFailed()
