parameters:
  dependsOn: 'Build'
  pesterVersion: ''
  testsDirectory: '$(Build.SourcesDirectory)/Tests'
  includeTag: []
  excludeTag: []
  additionalModulePath: ''
  artifactName: 'Module'
  stagingDirectory: '$(Build.ArtifactStagingDirectory)'
  codeCoverageDirectory: '$(Build.ArtifactStagingDirectory)'
  show: 'All'
  pool:
    vmImage: 'windows-2019'

jobs:
  - job: Pester
    dependsOn: ${{ parameters.dependsOn }}

    pool: ${{ parameters.pool }}

    steps:
    - checkout: self
      lfs: true

    - template: InstallRequiredModules-step.yml
      parameters:
        Destination: $(Build.SourcesDirectory)/RequiredModules

    # If Pester depends on a build step, then we should download that artifact
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Build Artifacts'
      condition: ${{ ne('', parameters.artifactName)}}
      inputs:
        artifactName: ${{ parameters.artifactName }}
        downloadPath: ${{ parameters.artifactDownloadDirectory }}

    - template: Pester-step.yml
      parameters:
        pesterVersion: ${{ parameters.pesterVersion }}
        testsDirectory: ${{ parameters.testsDirectory }}
        includeTag: ${{ parameters.includeTag }}
        excludeTag: ${{ parameters.excludeTag }}
        additionalModulePath: ${{ parameters.additionalModulePath }}
        codeCoverageDirectory: ${{ parameters.codeCoverageDirectory }}
        show: ${{ parameters.show }}
